# Generated by Django 3.2.7 on 2021-10-02 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IgUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('ftime', models.TimeField(blank=True, null=True, verbose_name='From Time')),
                ('ttime', models.TimeField(blank=True, null=True, verbose_name='To Time')),
                ('cookie', models.JSONField(blank=True, null=True)),
                ('pro_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('b_id', models.CharField(blank=True, max_length=50, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('counter2', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='description mentions')),
                ('comment', models.CharField(blank=True, default='FOLLOW ME🌟🌟 FOLLOW BACK SURE👍  ', max_length=500, null=True)),
                ('proxy', models.CharField(blank=True, help_text='https://username:password@ip:port', max_length=100, null=True, verbose_name='proxy')),
            ],
        ),
        migrations.CreateModel(
            name='SlaveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('cookie', models.JSONField(blank=True, null=True)),
                ('pro_pic', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Success', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('ig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iguser')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddField(
            model_name='iguser',
            name='slave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.slaveuser'),
        ),
    ]
