# Generated by Django 3.2.7 on 2021-10-31 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211029_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='IG/Images'),
        ),
        migrations.CreateModel(
            name='PicShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='IG/Shedule')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('iguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.iguser')),
            ],
        ),
    ]
