# Generated by Django 3.2.7 on 2021-10-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211031_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='picshedule',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
