# Generated by Django 3.2.7 on 2021-11-04 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_picshedule_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='iguser',
            name='live_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='picshedule',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
